name: Build & Release APK

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Rename APK with version tag
        run: mv app/build/outputs/apk/debug/app-debug.apk PoetryHelper-${{ github.ref_name }}.apk

      - name: List APKs (debug)
        run: ls -R app/build/outputs/apk

      - name: Upload APK to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: PoetryHelper-${{ github.ref_name }}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
